version:    '3.8'

services:
    # Go Application
    api:
        build: .    # Build the Docker image from the current directory
        ports:
            - ${PORT:-8080}:${PORT:-8080}  # Map port 8080 of the container to port 8080 on the host
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started
        environment:
            - REDIS_ADDR=${REDIS_ADDR} # Set the Redis address for the API Service
            - DB_HOST=db
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_PORT=${DB_PORT}
    
    # Redis Service
    redis:
        image: "redis:alpine" # Use the official Redis image from Docker Hub
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}   # Map port 6379 of the container to port 6379 on the host
    # PostgreSQL Service
    db:
      image: "postgres:alpine" # Use the official PostgreSQL image from Docker Hub
      restart: always
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - ${DB_PORT}:${DB_PORT} # Map port 5432 of the container
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
        interval: 5s
        timeout: 5s
        retries: 5
